language: node_js
node_js:
  - '10'
cache: yarn
script:
  - yarn storybook:build
# after_success:
  # - yarn coveralls
deploy:
  provider: pages
  local_dir: example
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  email: false